site_name: DAA for Kids
theme:
  name: material
  palette:
    - scheme: slate
      primary: black      # Keep header black
      accent: custom      # Custom accent for links/buttons/etc.
extra_css:
  - stylesheets/extra.css
nav:
  - Introduction: index.md
  - Installation: installation.md
  - Components:
    - Pathfinding Algorithms: components/pathfinding.md
    - Knapsack Problem: components/knapsack.md
    - Longest Common Subsequence: components/lcs.md
    - Huffman Encoding: components/huffman.md
  - Usage: usage.md
  - Examples: examples.md
  - Contributing: contributing.md
  - Changelog: changelog.md
