site_name: DAA for Kids
theme:
  name: material
  palette:
    - scheme: slate
      primary: black      # Keep header black
      accent: custom      # Custom accent for links/buttons/etc.
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - Introduction: introduction.md
  - Components: components.md
  - Problems: problems.md
  - Solution: solution.md
  - Installation: installation.md
  - Usage: usage.md
  - Examples: examples.md
  - Contributing: contributing.md
  - License: license.md
  - Changelog: changelog.md
